create table users (
    id bigint generated by default as identity,
    password varchar(255),
    username varchar(255),
    primary key (id)
);

create table filter (
    id bigint generated by default as identity,
    name varchar(255),
    user_id bigint not null, -- Ensure filter is always associated with a user
    primary key (id),
    unique (user_id, name) -- Optional: ensure unique filter names for each user
);

create table criteria (
    criteria_type varchar(31) not null,
    id bigint generated by default as identity,
    amount integer,
    comparison_type tinyint check (comparison_type between 0 and 5),
    date date,
    title varchar(255),
    filter_id bigint not null, -- Ensure criteria is always associated with a filter
    primary key (id),
    foreign key (filter_id) references filter(id) -- Add the foreign key constraint
);

-- alter table if exists filter add constraint FK_user_id foreign key (user_id) references users(id);

-- Insert user
INSERT INTO USERS (username, password) VALUES ('kadri', 'password123');

-- Insert filters
INSERT INTO FILTER (id, name, user_id) VALUES (703948, 'TestFilter', 1);
INSERT INTO FILTER (id, name, user_id) VALUES (703947,'SecondFilter', 1);
INSERT INTO FILTER (id, name, user_id) VALUES (703946,'ThirdFilter', 1);
INSERT INTO FILTER (id, name, user_id) VALUES (703945,'FourthFilter', 1);

-- Insert filter criteria for the first filter (TestFilter)
INSERT INTO CRITERIA (filter_id, criteria_type, amount, comparison_type, title, date) VALUES
(703948, 'AmountCriteria', 5, 0, NULL, NULL),
(703948, 'TitleCriteria', NULL, 4, 'First', NULL),
(703948, 'DateCriteria', NULL, 0, NULL, '2024-10-02');

-- Insert filter criteria for the second filter (SecondFilter)
INSERT INTO CRITERIA (filter_id, criteria_type, amount, comparison_type, title, date) VALUES
(703947, 'AmountCriteria', 500, 1, NULL, NULL),
(703947, 'TitleCriteria', NULL, 5, 'riot', NULL),
(703947, 'DateCriteria', NULL, 1, NULL, '2024-11-01');

-- Insert filter criteria for the third filter (ThirdFilter)
INSERT INTO CRITERIA (filter_id, criteria_type, amount, comparison_type, title, date) VALUES
(703946, 'TitleCriteria', NULL, 4, 'Once upon a time', NULL),
(703946, 'AmountCriteria', 1000, 1, NULL, NULL),
(703946, 'DateCriteria', NULL, 0, NULL, '2022-01-21');

-- Insert filter criteria for the fourth filter (FourthFilter)
INSERT INTO CRITERIA (filter_id, criteria_type, amount, comparison_type, title, date) VALUES
(703945, 'TitleCriteria', NULL, 4, 'It was the best of times', NULL),
(703945, 'AmountCriteria', 33, 0, NULL, NULL),
(703945, 'DateCriteria', NULL, 2, NULL, '2024-01-01');
